### ISSUE TITLE
Can't build this on mac os

### ISSUE THREAD

**Issue by Absinthe8383** [awused/aw-man#3]
As the title says I can't build this on mac Os, I think its because of gtk, I have tried installing that but no help, is there a way to make this work on mac? 

![Screenshot 2022-12-22 at 17 33 09](https://user-images.githubusercontent.com/116995336/209131268-4b6d6257-ae50-4798-9fd7-a6826df53edf.png)

**Comment by awused** [comment]
Yeah I've never tried to build it on mac, but this particular error looks straightforward enough. I pushed a new commit that should prevent it trying to link `gtk4-x11` on mac. I may be slow to respond over the holidays but I can at least try to resolve build errors, though no promises that everything just works seamlessly even when it does build.

**Comment by Absinthe8383** [comment]
Thanks for the quick reply now another error occurs, actually I tried to build this on debian once and had to installed around 30 packages manually after finding what is missing but still wasn't able to successfully build it. here is the screenshot and do take your time to reply, no worries. 

![Screenshot 2022-12-24 at 00 37 27](https://user-images.githubusercontent.com/116995336/209396379-3a86ebb3-87fb-4be9-aceb-9827682921ba.png)

I tried to solve by exporting flags as mentioned in homebrew for config path but still no success, I will try to look more into it as this sounds more of a mac issue rather than rust's.

**Comment by awused** [comment]
I'm surprised it took so many libraries, at least on my system it was only a couple of additional libraries.

I'm not familiar with homebrew or macos development. What is the output from that command (`pkg-config --libs --cflags libarchive`) run manually?

If you can find the libarchive.pc file you can add it to PKG_CONFIG_PATH.

**Comment by Absinthe8383** [comment]
> I'm surprised it took so many libraries, at least on my system it was only a couple of additional libraries.
> 
> I'm not familiar with homebrew or macos development. What is the output from that command (`pkg-config --libs --cflags libarchive`) run manually?
> 
> If you can find the libarchive.pc file you can add it to PKG_CONFIG_PATH.

So I find `libarchive.pc` by digging some directories, and now the same this occurs for `libiconv` and there is no `iconv.pc` file in any of the directories so I unintalled it and downloded from gnu website but the result is still the same, so I am stuck.

**Comment by awused** [comment]
Yeah that just sounds like an issue installing libraries or getting pkg-config to work on mac. Maybe it's failing to write to /usr/local/include during installation? I have no experience developing on mac and I'm not sure I can help you much there. You could eventually work through every package but it'll be annoying and probably not worth it, better to figure out why homebrew isn't working nicely with pkg-config since I'd expect them to work together.

Just to be sure if you want to go through the effort, I'd characterize aw-man as being a lot like mcomix/honeyview, at least how I used them. Less customization and any features I don't personally use weren't implemented, but what remains is faster, lighter, and higher quality (correct downscaling, etc).

**Comment by Absinthe8383** [comment]
> Yeah that just sounds like an issue installing libraries or getting pkg-config to work on mac. Maybe it's failing to write to /usr/local/include during installation? I have no experience developing on mac and I'm not sure I can help you much there. You could eventually work through every package but it'll be annoying and probably not worth it, better to figure out why homebrew isn't working nicely with pkg-config since I'd expect them to work together.
> 
> Just to be sure if you want to go through the effort, I'd characterize aw-man as being a lot like mcomix/honeyview, at least how I used them. Less customization and any features I don't personally use weren't implemented, but what remains is faster, lighter, and higher quality (correct downscaling, etc).

So by using some shenanigan, I was able to build aw-man, it was libarchive fault for iconv.pc when the program doesn't even make that file, but now I am getting a new error that is the courtesy of jellamoc, this shitty mac ventura update is giving me all kinds of errors, that's why I love my linux machine

**Comment by Absinthe8383** [comment]
# https://github.com/jemalloc/jemalloc/issues/2362

**Comment by Absinthe8383** [comment]
jemalloc/jemalloc#2362

![Screenshot](https://user-images.githubusercontent.com/116995336/209855295-9bb71e05-b61e-4ff8-8472-dd7297d30cb4.png)

also a side-question, can I disable manga-syncer? Because I just want to use this as reader and offline

**Comment by awused** [comment]
I disabled jemalloc for mac, though since I use jemalloc for predictable performance especially around deallocations I can't tell you for certain how it will perform. It should still be fast enough to not be perceivable but I can't directly benchmark on Mac myself.

As for manga-syncer, there isn't anything directly tying aw-man to manga-syncer besides the regex for sorting chapters by number.

**Comment by Absinthe8383** [comment]
> I disabled jemalloc for mac, though since I use jemalloc for predictable performance especially around deallocations I can't tell you for certain how it will perform. It should still be fast enough to not be perceivable but I can't directly benchmark on Mac myself.
> 
> As for manga-syncer, there isn't anything directly tying aw-man to manga-syncer besides the regex for sorting chapters by number.

thanks for the clarifcation, I build it but the 2nd line from the previous is still there `thread 'main' panicked at 'NotFound', src/config/mod.rs:189:13` when running the program.

**Comment by awused** [comment]
That means it couldn't find your config file. I never built it to run without a config file at all so you'll need to follow the instructions in the readme. The error could be a bit more clear about what it couldn't find.

**Comment by Absinthe8383** [comment]
> That means it couldn't find your config file. I never built it to run without a config file at all so you'll need to follow the instructions in the readme. The error could be a bit more clear about what it couldn't find.

![Screenshot 2022-12-30 at 21 10 07](https://user-images.githubusercontent.com/116995336/210087665-9c0828c5-f410-4765-acf7-99981d640bb3.png)

**Comment by Absinthe8383** [comment]
> That means it couldn't find your config file. I never built it to run without a config file at all so you'll need to follow the instructions in the readme. The error could be a bit more clear about what it couldn't find.
![Screenshot 2022-12-30 at 21 12 11](https://user-images.githubusercontent.com/116995336/210087792-a660551f-f43f-4abe-9277-b98c18617a3c.png)

**Comment by awused** [comment]
For that it needs to dynamically load libepoxy, I should add that to the readme but it seems Mac might be the only platform where it's not natively available.

**Comment by Absinthe8383** [comment]
> I disabled jemalloc for mac, though since I use jemalloc for predictable performance especially around deallocations I can't tell you for certain how it will perform. It should still be fast enough to not be perceivable but I can't directly benchmark on Mac myself.
> 
> As for manga-syncer, there isn't anything directly tying aw-man to manga-syncer besides the regex for sorting chapters by number.

Sorry for the late reply, I found manga reader that works on mac too, maybe you can take a look at that as it doesn't even have dependencies for mac. 
https://github.com/rsuu/rmg

I am closing this issue now, as this is not related to the actual question.

**Comment by awused** [comment]
I looked into it. It does rely on some external binaries in place of libarchive, has a less complicated gui without the need for libgtk, and doesn't use the gpu for rendering hence no need for libepoxy. It bears a lot of similarities to how I built the initial versions of aw-man before putting more effort into features and performance. There is not much for me to take from it, since I'd have to drop the functionality I use to drop those dependencies.

I was willing to help resolve build issues on a best-effort basis, but this is a personal project for myself, as stated in my readme. I will not change it to make it easier to build on platforms I don't use.

**Comment by Absinthe8383** [comment]
> I looked into it. It does rely on some external binaries in place of libarchive, has a less complicated gui without the need for libgtk, and doesn't use the gpu for rendering hence no need for libepoxy. It bears a lot of similarities to how I built the initial versions of aw-man before putting more effort into features and performance. There is not much for me to take from it, since I'd have to drop the functionality I use to drop those dependencies.
> 
> I was willing to help resolve build issues on a best-effort basis, but this is a personal project for myself, as stated in my readme. I will not change it to make it easier to build on platforms I don't use.

Yeah I understand, thanks either way :)
